management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23lihltlLfMV5D0mNl
            clientSecret: c8472e7eadf271e2dc05793d8ccf818d5d0b6268
